dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8
  - oraclejdk9

notifications:
  email: acogoluegnes@pivotal.io
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - esl-erlang=1:20.1
services:
  - rabbitmq
branches:
  only:
    - master
before_script:
  - ./bin/install_on_debian.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
script: ./gradlew check -i -s
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: true
