dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8
  - oraclejdk9

notifications:
  email: acogoluegnes@pivotal.io
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
      - sourceline: deb https://dl.bintray.com/rabbitmq/debian trusty main
        key_url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    packages:
      - esl-erlang=1:20.1
# because of https://github.com/travis-ci/travis-ci/issues/8906
before_install:
  - sudo mv /opt/jdk_switcher/jdk_switcher.sh /tmp
  - sudo apt-get install rabbitmq-server=3.7.0-1
  - sudo mv /tmp/jdk_switcher.sh /opt/jdk_switcher/
services:
  - rabbitmq
branches:
  only:
    - master

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
script: ./gradlew check -i -s
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: true
